-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 22:18:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipment` (
  `id` INT NOT NULL,
  `eq_type` VARCHAR(30) NOT NULL,
  `eq_name` VARCHAR(30) NOT NULL,
  `eq_cost` FLOAT NOT NULL,
  `eq_weight` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch office` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manager` (
  `id` INT NOT NULL,
  `man_Fname` VARCHAR(30) NOT NULL,
  `man_Lname` VARCHAR(30) NOT NULL,
  `man_MI` VARCHAR(2) NOT NULL,
  `man_address` VARCHAR(45) NOT NULL,
  `man_sex` VARCHAR(15) NOT NULL,
  `month_salary` FLOAT NOT NULL,
  `branch office_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_manager_branch office_idx` (`branch office_id` ASC) VISIBLE,
  CONSTRAINT `fk_manager_branch office`
    FOREIGN KEY (`branch office_id`)
    REFERENCES `mydb`.`branch office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member bio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member bio` (
  `id` INT NOT NULL,
  `mem_fat` FLOAT NOT NULL,
  `mem_muscle` FLOAT NOT NULL,
  `mem_weight` FLOAT NOT NULL,
  `mem_age` INT NOT NULL,
  `mem_height` FLOAT NOT NULL,
  `record_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member payment` (
  `id` INT NOT NULL,
  `pay_amount` FLOAT NOT NULL,
  `pay_date` DATE NOT NULL,
  `pay_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `id` INT NOT NULL,
  `emp_Fname` VARCHAR(30) NOT NULL,
  `emp_Fname` VARCHAR(30) NOT NULL,
  `emp_MI` VARCHAR(2) NOT NULL,
  `emp_add` VARCHAR(45) NOT NULL,
  `emp_sex` VARCHAR(15) NOT NULL,
  `week_salary` FLOAT NOT NULL,
  `manager_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_staff_manager1_idx` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
