-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 19:17:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch` (
  `id` INT NOT NULL,
  `branch_name` VARCHAR(25) NULL,
  `branch_address` VARCHAR(45) NULL,
  `branch_phone` BIGINT(8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipment` (
  `id` INT NOT NULL,
  `eq_type` VARCHAR(30) NOT NULL,
  `eq_name` VARCHAR(30) NOT NULL,
  `eq_cost` FLOAT NOT NULL,
  `eq_weight` FLOAT NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_equipment_branch1_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch office` (
  `id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_branch office_branch1_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_branch office_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manager` (
  `id` INT NOT NULL,
  `man_Fname` VARCHAR(30) NOT NULL,
  `man_Lname` VARCHAR(30) NOT NULL,
  `man_MI` VARCHAR(2) NOT NULL,
  `man_address` VARCHAR(45) NOT NULL,
  `man_sex` VARCHAR(15) NOT NULL,
  `month_salary` FLOAT NOT NULL,
  `branch_id` INT NOT NULL,
  `branch office_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_manager_branch1_idx` (`branch_id` ASC) VISIBLE,
  INDEX `fk_manager_branch office1_idx` (`branch office_id` ASC) VISIBLE,
  CONSTRAINT `fk_manager_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manager_branch office1`
    FOREIGN KEY (`branch office_id`)
    REFERENCES `mydb`.`branch office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`batch` (
  `id` INT NOT NULL,
  `batch_type` VARCHAR(20) NULL,
  `batch_start` DATETIME NULL,
  `batch_end` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trainer` (
  `id` INT NOT NULL,
  `train_fname` VARCHAR(15) NULL,
  `train_lname` VARCHAR(15) NULL,
  `train_mi` VARCHAR(15) NULL,
  `train_address` VARCHAR(45) NULL,
  `train_sex` VARCHAR(6) NULL,
  `train_hoursalary` INT NULL,
  `branch_id` INT NOT NULL,
  `manager_id` INT NOT NULL,
  `branch office_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trainer_branch1_idx` (`branch_id` ASC) VISIBLE,
  INDEX `fk_trainer_manager1_idx` (`manager_id` ASC) VISIBLE,
  INDEX `fk_trainer_branch office1_idx` (`branch office_id` ASC) VISIBLE,
  CONSTRAINT `fk_trainer_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainer_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainer_branch office1`
    FOREIGN KEY (`branch office_id`)
    REFERENCES `mydb`.`branch office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `id` INT NOT NULL,
  `mem_fname` VARCHAR(15) NULL,
  `mem_lname` VARCHAR(15) NULL,
  `mem_mi` VARCHAR(15) NULL,
  `mem_address` VARCHAR(45) NULL,
  `mem_sex` VARCHAR(6) NULL,
  `batch_id` INT NOT NULL,
  `trainer_id` INT NOT NULL,
  `manager_id` INT NOT NULL,
  `branch office_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_member_batch_idx` (`batch_id` ASC) VISIBLE,
  INDEX `fk_member_trainer1_idx` (`trainer_id` ASC) VISIBLE,
  INDEX `fk_member_manager1_idx` (`manager_id` ASC) VISIBLE,
  INDEX `fk_member_branch office1_idx` (`branch office_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_batch`
    FOREIGN KEY (`batch_id`)
    REFERENCES `mydb`.`batch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_trainer1`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `mydb`.`trainer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_branch office1`
    FOREIGN KEY (`branch office_id`)
    REFERENCES `mydb`.`branch office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member bio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member bio` (
  `id` INT NOT NULL,
  `mem_fat` FLOAT NOT NULL,
  `mem_muscle` FLOAT NOT NULL,
  `mem_weight` FLOAT NOT NULL,
  `mem_age` INT NOT NULL,
  `mem_height` FLOAT NOT NULL,
  `record_date` DATE NOT NULL,
  `member_id` INT NOT NULL,
  `trainer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_member bio_member1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_member bio_trainer1_idx` (`trainer_id` ASC) VISIBLE,
  CONSTRAINT `fk_member bio_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member bio_trainer1`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `mydb`.`trainer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member payment` (
  `id` INT NOT NULL,
  `pay_amount` FLOAT NOT NULL,
  `pay_date` DATE NOT NULL,
  `pay_type` VARCHAR(10) NOT NULL,
  `member_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_member payment_member1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_member payment_branch1_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_member payment_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member payment_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `id` INT NOT NULL,
  `emp_Fname` VARCHAR(30) NOT NULL,
  `emp_Fname` VARCHAR(30) NOT NULL,
  `emp_MI` VARCHAR(2) NOT NULL,
  `emp_add` VARCHAR(45) NOT NULL,
  `emp_sex` VARCHAR(15) NOT NULL,
  `week_salary` FLOAT NOT NULL,
  `manager_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_staff_manager1_idx` (`manager_id` ASC) VISIBLE,
  INDEX `fk_staff_branch1_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`batch_has_trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`batch_has_trainer` (
  `batch_id` INT NOT NULL,
  `trainer_id` INT NOT NULL,
  PRIMARY KEY (`batch_id`, `trainer_id`),
  INDEX `fk_batch_has_trainer_trainer1_idx` (`trainer_id` ASC) VISIBLE,
  INDEX `fk_batch_has_trainer_batch1_idx` (`batch_id` ASC) VISIBLE,
  CONSTRAINT `fk_batch_has_trainer_batch1`
    FOREIGN KEY (`batch_id`)
    REFERENCES `mydb`.`batch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batch_has_trainer_trainer1`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `mydb`.`trainer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_has_branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_has_branch` (
  `member_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`member_id`, `branch_id`),
  INDEX `fk_member_has_branch_branch1_idx` (`branch_id` ASC) VISIBLE,
  INDEX `fk_member_has_branch_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_has_branch_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_branch_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_has_equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_has_equipment` (
  `member_id` INT NOT NULL,
  `equipment_id` INT NOT NULL,
  PRIMARY KEY (`member_id`, `equipment_id`),
  INDEX `fk_member_has_equipment_equipment1_idx` (`equipment_id` ASC) VISIBLE,
  INDEX `fk_member_has_equipment_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_has_equipment_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_equipment_equipment1`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `mydb`.`equipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_has_branch1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_has_branch1` (
  `member_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`member_id`, `branch_id`),
  INDEX `fk_member_has_branch1_branch1_idx` (`branch_id` ASC) VISIBLE,
  INDEX `fk_member_has_branch1_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_has_branch1_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_branch1_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
