-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 08:37:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`batch` (
  `id` INT NOT NULL,
  `batch_type` VARCHAR(20) NULL,
  `batch_start` DATETIME NULL,
  `batch_end` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch` (
  `id` INT NOT NULL,
  `branch_name` VARCHAR(25) NULL,
  `branch_address` VARCHAR(45) NULL,
  `branch_phone` BIGINT(8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trainer` (
  `id` INT NOT NULL,
  `train_fname` VARCHAR(15) NULL,
  `train_lname` VARCHAR(15) NULL,
  `train_mi` VARCHAR(15) NULL,
  `train_address` VARCHAR(45) NULL,
  `train_sex` VARCHAR(6) NULL,
  `train_hoursalary` INT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trainer_branch1_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_trainer_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `id` INT NOT NULL,
  `mem_fname` VARCHAR(15) NULL,
  `mem_lname` VARCHAR(15) NULL,
  `mem_mi` VARCHAR(15) NULL,
  `mem_address` VARCHAR(45) NULL,
  `mem_sex` VARCHAR(6) NULL,
  `batch_id` INT NOT NULL,
  `trainer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_member_batch_idx` (`batch_id` ASC) VISIBLE,
  INDEX `fk_member_trainer1_idx` (`trainer_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_batch`
    FOREIGN KEY (`batch_id`)
    REFERENCES `mydb`.`batch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_trainer1`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `mydb`.`trainer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`batch_has_trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`batch_has_trainer` (
  `batch_id` INT NOT NULL,
  `trainer_id` INT NOT NULL,
  PRIMARY KEY (`batch_id`, `trainer_id`),
  INDEX `fk_batch_has_trainer_trainer1_idx` (`trainer_id` ASC) VISIBLE,
  INDEX `fk_batch_has_trainer_batch1_idx` (`batch_id` ASC) VISIBLE,
  CONSTRAINT `fk_batch_has_trainer_batch1`
    FOREIGN KEY (`batch_id`)
    REFERENCES `mydb`.`batch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batch_has_trainer_trainer1`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `mydb`.`trainer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_has_branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_has_branch` (
  `member_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`member_id`, `branch_id`),
  INDEX `fk_member_has_branch_branch1_idx` (`branch_id` ASC) VISIBLE,
  INDEX `fk_member_has_branch_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_has_branch_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_branch_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
